server:
  port: 8081

# 数据库连接池
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.17.18.37:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

xxl:
  job:
    admin:
      # 集群的填写方式
      #addresses: http://10.17.18.37:8080/xxl-job-admin,http://10.17.18.37:8088/xxl-job-admin
      addresses: http://10.17.18.37:8080/xxl-job-admin
    executor:
      # 执行器的appname
      appname: xxl-job-winning
      # 对外使用的ip
      ip: 10.17.18.37
      # 对外使用的端口号
      port: 8888
      # 日志存放的位置
      logpath: "/data/applogs/xxl-job/jobhandler"
      # 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；
      logretentiondays: -1
    #  执行器通讯TOKEN [选填]：非空时启用；
    accessToken: 111
  # 版本
  version: 1.0.0

logging:
  config: classpath:logback.xml
