
server:
  port: 7000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://10.17.18.37:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

xxl:
  job:
    admin:
      addresses: http://10.17.18.37:8080/xxl-job-admin,http://10.17.18.37:8088/xxl-job-admin
    executor:
      appname: xxl-job-winning
      ip: 10.17.18.37
      port: 8899
      logpath: "/data/applogs/xxl-job/jobhandler"
      logretentiondays: -1
    accessToken: 111
  version: 1.0.0

logging:
  config: classpath:logback.xml